#!/bin/bash

echo "Running blockMesh..."
blockMesh 2>&1 | tee log.blockMesh
echo "Running checkMesh..."
checkMesh 2>&1 | tee log.checkMesh
echo "Running solver..."
foamRun 2>&1 | tee log.foamRun

echo "Simulation finished."
